sudo: required
language: python
python:
  - '3.6'
services:
  - docker

before_install:
- docker build -t potboiler_img .
- docker ps -a

script:
  - docker run -it -d --rm --name potboiler_container potboiler_img /bin/bash
  - docker exec -it potboiler_container pytest --cov=potboiler
  - docker cp potboiler_container:/app/.coverage .

after_success:
  - coveralls
