sudo: required
language: python
python:
  - '3.6'
services:
  - docker

before_install:
- docker build -t potboiler .
- docker ps -a

script:
  - docker run -it --rm -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" potboiler "pytest --cov=potboiler; coveralls"

